spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 946667839607-1htit9pgisk2rtvon322538s5mhq2nd1.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          kakao:
            client-id: 5730a1d7ea4152f5623e1a8dec2cef57
            redirect-uri: http://localhost:8080/auth-service/login/oauth2/code/kakao # http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname #, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id