# Generated by Django 3.2.12 on 2022-09-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedPainting',
            fields=[
                ('changed_painting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('member_id', models.BigIntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'changed_painting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailRecommendedPainting',
            fields=[
                ('detail_recommended_painting_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detail_recommended_painting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikedPainting',
            fields=[
                ('liked_painting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_id', models.BigIntegerField(blank=True, null=True)),
                ('painting_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'liked_painting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('painting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('art_trend', models.CharField(blank=True, max_length=255, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('hits', models.BigIntegerField(blank=True, null=True)),
                ('korean_title', models.CharField(blank=True, max_length=255, null=True)),
                ('medium', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('total_change_count', models.BigIntegerField(blank=True, null=True)),
                ('total_like_count', models.BigIntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'painting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendedPainting',
            fields=[
                ('liked_painting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommended_painting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelectedPainting',
            fields=[
                ('selected_painting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'selected_painting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteStyle',
            fields=[
                ('painting', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recommend_art.painting')),
            ],
            options={
                'db_table': 'favorite_style',
                'managed': False,
            },
        ),
    ]
