# Generated by Django 3.2.12 on 2022-09-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('painting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('dimesions', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('hits', models.BigIntegerField(blank=True, null=True)),
                ('medium', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('year', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'painting',
                'managed': False,
            },
        ),
    ]
