# Generated by Django 3.2.12 on 2022-09-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_art', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedPainting',
            fields=[
                ('changed_painting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'changed_painting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteStyle',
            fields=[
                ('favorite_style_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favorite_style',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelectedPainting',
            fields=[
                ('selected_painting_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'selected_painting',
                'managed': False,
            },
        ),
    ]
