# Generated by Django 3.2.12 on 2022-09-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_art', '0002_uploadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='testfield',
        ),
    ]
