# Generated by Django 3.2.12 on 2022-09-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_art', '0003_remove_uploadimage_testfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
