# Generated by Django 3.2.12 on 2022-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_art', '0004_alter_uploadimage_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('click_count', models.BigIntegerField(blank=True, null=True)),
                ('in_time', models.CharField(blank=True, max_length=255, null=True)),
                ('member_id', models.BigIntegerField(blank=True, null=True)),
                ('out_time', models.CharField(blank=True, max_length=255, null=True)),
                ('painting_id', models.BigIntegerField(blank=True, null=True)),
                ('zoom_count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member_log',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
